name = "QiILS"
uuid = "827905d2-d693-4b35-89a3-0018b3a7522a"
authors = ["gpreisser <guillermopreisser@hotmail.com>"]
version = "0.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Graphs = "1.13.1"
JSON = "1.3.0"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
SimpleWeightedGraphs = "1.5.0"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
